// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.
// END EXTRA CODE

/**
 * Manual unlock — the fallback button, not the main path.
 *
 * Tap-and-go never reaches here: the SDK opens the door on proximity with the
 * app closed and no JavaScript running. Use this for lifts, gates, and taps
 * that did not land.
 *
 * Studio Pro parameters:
 *   cardId  String  (optional — omit to use the only credential)
 * Returns: String (JSON) {"ok":true,"result":"opened"} where result is
 *   opened | noReader | denied. On failure, code is one of E_BT_OFF,
 *   E_PERMISSION, E_NO_CARD, E_NO_READER, E_LICENCE.
 *
 * @param {string} cardId
 * @returns {Promise.<string>}
 */
export async function AirfobUnlock(cardId) {
    // BEGIN USER CODE
    try {
        const result = await Airfob.unlock(cardId || undefined);
        return JSON.stringify({ ok: true, ...result });
    } catch (e) {
        return JSON.stringify({
            ok: false,
            code: e.code || "E_SDK",
            message: e.message || String(e)
        });
    }
    // END USER CODE
}
