// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.
// END EXTRA CODE

/**
 * Build a support bundle: the on-device log plus the context that explains it.
 *
 * Attach the returned "bundle" string to a FileDocument, or store it on a
 * support-ticket entity. This is what turns "it didn't work" into something a
 * support engineer can act on.
 *
 * BLE access control fails silently, in a pocket, on a handset you do not have.
 * The log survives process death precisely because the failing tap happened
 * hours before the user opened the app to complain.
 *
 * Access logs are personal data. Agree a retention period before P4 wires this
 * to a backend entity.
 *
 * Studio Pro parameters:
 *   contextJson  String  (optional) extra fields, e.g. {"user":"..."}
 * Returns: String (JSON) {"ok":true,"path":"...","entryCount":42,"bundle":"..."}
 *   where "bundle" is the full JSON blob to persist. "path" is the on-device
 *   file, or empty when there is no native module to write one.
 *
 * @param {string} contextJson
 * @returns {Promise.<string>}
 */
export async function AirfobExportLog(contextJson) {
    // BEGIN USER CODE
    let context = {};
    if (contextJson) {
        try {
            context = JSON.parse(contextJson);
        } catch (e) {
            return JSON.stringify({
                ok: false,
                code: "E_BAD_PAYLOAD",
                message: "contextJson is not valid JSON"
            });
        }
    }

    try {
        const bundle = await Airfob.log.export(context);
        return JSON.stringify({
            ok: true,
            path: bundle.path || "",
            entryCount: bundle.content.entryCount,
            bundle: JSON.stringify(bundle.content)
        });
    } catch (e) {
        return JSON.stringify({
            ok: false,
            code: e.code || "E_SDK",
            message: e.message || String(e)
        });
    }
    // END USER CODE
}
