// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.
// END EXTRA CODE

/**
 * Every precondition that has to hold before a tap can open a door.
 *
 * Each check carries either an "action" to hand to AirfobRemediate, or a
 * "remedy" string to show the user. Render both when present — on iOS the
 * button only reaches the app settings page, so the words are what tell the
 * user what to change.
 *
 * Nulls are normalised to empty strings so the Mendix import mapping produces
 * String attributes rather than failing to infer a type.
 *
 * Returns: String (JSON). Deserialize with the AirfobDiagnostics import mapping.
 *
 * @returns {Promise.<string>}
 */
export async function AirfobGetDiagnostics() {
    // BEGIN USER CODE
    try {
        const diagnostics = await Airfob.getDiagnostics();
        return JSON.stringify({
            ok: true,
            summary: diagnostics.summary,
            devicePlatform: diagnostics.device.platform,
            deviceModel: diagnostics.device.model,
            deviceOsVersion: diagnostics.device.osVersion,
            checks: diagnostics.checks.map(check => ({
                id: check.id,
                label: check.label,
                state: check.state,
                detail: check.detail || "",
                action: check.action || "",
                actionLabel: check.actionLabel || "",
                remedy: check.remedy || ""
            }))
        });
    } catch (e) {
        return JSON.stringify({
            ok: false,
            code: e.code || "E_SDK",
            message: e.message || String(e)
        });
    }
    // END USER CODE
}
