// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.
// END EXTRA CODE

/**
 * Current SDK state. Cheap — safe to call on every page show.
 *
 * Returns: String (JSON). Deserialize with the AirfobStatus import mapping.
 *   {"ok":true,"sdkReady":true,"mock":false,"registered":true,
 *    "bluetooth":"on","permissions":"granted","licence":"valid",
 *    "cardCount":1,"version":"0.2.0"}
 *
 * @returns {Promise.<string>}
 */
export async function AirfobGetStatus() {
    // BEGIN USER CODE
    try {
        const status = await Airfob.getStatus();
        return JSON.stringify({ ok: true, ...status });
    } catch (e) {
        return JSON.stringify({
            ok: false,
            code: e.code || "E_SDK",
            message: e.message || String(e)
        });
    }
    // END USER CODE
}
