// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.

// Rewritten by the installer when --module is used. Keep on one line.
const AIRFOB_MODULE = "Airfob";

// END EXTRA CODE

/**
 * Start the Airfob SDK. Idempotent and safe to call from any page.
 *
 * Call this from the home page on-load nanoflow. Mendix After Startup runs a
 * MICROFLOW, server-side, which cannot reach a JavaScript action — and it is not
 * needed anyway: the SDK already boots in native code at process launch, which
 * is what makes tap-and-go work with the app closed. This is a safety net.
 *
 * Studio Pro
 *   siteId                   String   (optional)
 *   logLevel                 String   (optional) off | error | warn | info | debug
 *   correlationId            String   (optional) ties this device to the token
 *                                     your backend issued — without it a failed
 *                                     unlock cannot be joined to its enrolment
 *   retentionDays            Integer  (optional) days of log kept, default 7.
 *                                     A privacy control: access logs record where
 *                                     a named person was and when. 0 keeps all.
 *   autoBundleAfterFailures  Integer  (optional) capture a support bundle after
 *                                     this many consecutive failed unlocks.
 *                                     0 (default) disables it.
 *   returns                  Boolean
 *
 * @param {string} siteId
 * @param {string} logLevel
 * @param {string} correlationId
 * @param {Big} retentionDays
 * @param {Big} autoBundleAfterFailures
 * @returns {Promise.<boolean>}
 */
export async function AirfobBoot(siteId, logLevel, correlationId, retentionDays, autoBundleAfterFailures) {
    // BEGIN USER CODE
    try {
        await Airfob.boot({
            siteId: siteId || undefined,
            logLevel: logLevel || undefined,
            correlationId: correlationId || undefined,
            retentionDays: retentionDays ? Number(retentionDays) : undefined,
            autoBundleAfterFailures: autoBundleAfterFailures ? Number(autoBundleAfterFailures) : undefined
        });
        return true;
    } catch (e) {
        Airfob.log.write("error", "bridge", e.code || "E_SDK", "AirfobBoot: " + e.message);
        return false;
    }
    // END USER CODE
}
