// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.

// Rewritten by the installer when --module is used. Keep on one line.
const AIRFOB_MODULE = "Airfob";

// END EXTRA CODE

/**
 * Start the Airfob SDK. Idempotent and safe to call from any page.
 *
 * Call this from the home page on-load nanoflow. Mendix After Startup runs a
 * MICROFLOW, server-side, which cannot reach a JavaScript action — and it is not
 * needed anyway: the SDK already boots in native code at process launch, which
 * is what makes tap-and-go work with the app closed. This is a safety net.
 *
 * Studio Pro
 *   siteId    String   (optional)
 *   logLevel  String   (optional) off | error | warn | info | debug
 *   returns   Boolean
 *
 * @param {string} siteId
 * @param {string} logLevel
 * @returns {Promise.<boolean>}
 */
export async function AirfobBoot(siteId, logLevel) {
    // BEGIN USER CODE
    try {
        await Airfob.boot({
            siteId: siteId || undefined,
            logLevel: logLevel || undefined
        });
        return true;
    } catch (e) {
        Airfob.log.write("error", "bridge", e.code || "E_SDK", "AirfobBoot: " + e.message);
        return false;
    }
    // END USER CODE
}
