// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.

// Rewritten by the installer when --module is used. Keep on one line.
const AIRFOB_MODULE = "Airfob";

/**
 * Nanoflows cannot call an import mapping — those activities are microflow-only —
 * and cannot parse JSON, so the action builds the Mendix object itself.
 * Every value must be non-null and already the right type for its attribute.
 */
function createAirfobObject(entityName, values) {
    return new Promise((resolve, reject) => {
        mx.data.create({
            entity: AIRFOB_MODULE + "." + entityName,
            callback: object => {
                Object.keys(values).forEach(key => object.set(key, values[key]));
                resolve(object);
            },
            error: reject
        });
    });
}

function airfobResult(ok, code, message, result) {
    return createAirfobObject("AirfobResult", {
        ok: ok,
        code: code || "",
        message: message || "",
        result: result || ""
    });
}

// END EXTRA CODE

/**
 * Build a support bundle: the on-device log plus the context that explains it.
 *
 * BLE access control fails silently, in a pocket, on a handset you do not have.
 * The log survives process death precisely because the failing tap happened
 * hours before the user opened the app to complain.
 *
 * Store the "bundle" string on a support-ticket entity or a FileDocument.
 * Access logs are personal data — agree a retention period before wiring this
 * to a backend in P4.
 *
 * Studio Pro
 *   contextJson  String  (optional) extra fields, e.g. {"user":"..."}
 *   returns      Object (Airfob.AirfobSupportBundle)
 *
 * @param {string} contextJson
 * @returns {Promise.<MxObject>}
 */
export async function AirfobExportLog(contextJson) {
    // BEGIN USER CODE
    let context = {};
    if (contextJson) {
        try {
            context = JSON.parse(contextJson);
        } catch (e) {
            return createAirfobObject("AirfobSupportBundle", {
                ok: false,
                code: "E_BAD_PAYLOAD",
                message: "contextJson is not valid JSON",
                pending: false,
                trigger: "",
                correlationId: "",
                retentionDays: 0,
                failureStreak: 0,
                path: "",
                entryCount: 0,
                droppedOlderEntries: 0,
                bundle: ""
            });
        }
    }

    try {
        const exported = await Airfob.log.export(context);
        const content = exported.content;
        return createAirfobObject("AirfobSupportBundle", {
            ok: true,
            code: "",
            message: "",
            pending: false,
            trigger: "manual",
            correlationId: content.correlationId || "",
            retentionDays: content.retentionDays || 0,
            failureStreak: 0,
            path: exported.path || "",
            entryCount: content.entryCount || 0,
            droppedOlderEntries: content.droppedOlderEntries || 0,
            bundle: JSON.stringify(content)
        });
    } catch (e) {
        return createAirfobObject("AirfobSupportBundle", {
            ok: false,
            code: e.code || "E_SDK",
            message: e.message || String(e),
            pending: false,
            trigger: "",
            correlationId: "",
            retentionDays: 0,
            failureStreak: 0,
            path: "",
            entryCount: 0,
            droppedOlderEntries: 0,
            bundle: ""
        });
    }
    // END USER CODE
}
