// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.
// END EXTRA CODE

/**
 * Put a credential on this device.
 *
 * The token comes from YOUR backend calling the Airfob API server-to-server.
 * Never issue it from the app — the Airfob API key must not ship in a mobile
 * binary. Typical nanoflow: call a microflow that returns the token, then pass
 * it here.
 *
 * Studio Pro parameters:
 *   token  String  (required)
 * Returns: String (JSON). Deserialize with the AirfobCards import mapping.
 *
 * @param {string} token
 * @returns {Promise.<string>}
 */
export async function AirfobRegister(token) {
    // BEGIN USER CODE
    if (!token) {
        return JSON.stringify({
            ok: false,
            code: "E_SDK",
            message: "AirfobRegister requires a token"
        });
    }

    try {
        const { cards } = await Airfob.register(token);
        // accessLevels is an array of strings; flattening it keeps the Mendix
        // import mapping one level deep instead of generating a child entity
        // for what is really a label.
        return JSON.stringify({
            ok: true,
            cards: cards.map(card => ({
                id: card.id,
                name: card.name,
                siteName: card.siteName,
                status: card.status,
                accessLevels: (card.accessLevels || []).join(", ")
            }))
        });
    } catch (e) {
        return JSON.stringify({
            ok: false,
            code: e.code || "E_SDK",
            message: e.message || String(e)
        });
    }
    // END USER CODE
}
