// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - anything outside of the class methods
//
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import Airfob from "react-native-airfob";

// BEGIN EXTRA CODE
// @airfob-generated — installed by "npx react-native-airfob install-mendix".
// Re-run that command to update; local edits here will be overwritten.
// END EXTRA CODE

/**
 * Open the OS settings screen that fixes a failing check.
 *
 * Pass the "action" value from an AirfobCheck. Bind the button caption to
 * "actionLabel" and make it visible only when "action" is not empty.
 *
 * Android lands on the exact screen. iOS can only open this app's settings
 * page, and has no per-app battery exemption at all, so openBatterySettings
 * returns false there. Always show the check's "remedy" text as well.
 *
 * Studio Pro parameters:
 *   actionId  String  (required)
 * Returns: Boolean — false means nothing was opened; show the remedy instead.
 *
 * @param {string} actionId
 * @returns {Promise.<boolean>}
 */
export async function AirfobRemediate(actionId) {
    // BEGIN USER CODE
    if (!actionId) {
        return false;
    }

    try {
        const { opened } = await Airfob.remediate(actionId);
        return !!opened;
    } catch (e) {
        Airfob.log.write("warn", "perm", e.code || "E_SDK", "AirfobRemediate: " + e.message);
        return false;
    }
    // END USER CODE
}
